### ISSUE TITLE
CTRMap-CE claims Pokemon White 2 is unsupported

### ISSUE THREAD

**Issue by m4-used-rollout** [kingdom-of-ds-hacking/CTRMap-CE#1]
I ripped my copy of Pokemon White 2 (USA) `sha1: 64ce6393493d0d5b3ba76027944eab58524ebbe2` and the program said it was unsupported:

![image](https://user-images.githubusercontent.com/1911304/208856547-ca68ae4d-2b5a-49f6-948a-9b9d8009efa0.png)

I had someone else try with their copy Pokemon - White Version 2 (USA, Europe) (NDSi Enhanced) `sha1: b5d7490be7b415b8f1e672a53e978a9cc667e56a` and got the same error.

I checked the headers and both identified themselves correctly: 
![image](https://user-images.githubusercontent.com/1911304/208857005-662dca66-9368-4430-8e1b-080d379c7395.png)

I know my copy of White 2 is legitimate because the C-Gear IR communication works on the cart.

**Comment by HelloOO7** [comment]
Indeed, CTRMap CE does not support Pokémon White 2 (or any games, really, but oh well) out of the box.

Instead, in order to load Pokémon ROM dumps, you're gonna want to install their support plug-in. That isn't part of CE, but can be obtained separately here: https://github.com/kingdom-of-ds-hacking/CTRMapV

Hope that helps.
-h7
