### ISSUE TITLE
Issue with shader compilation using AMD GPU drivers

### ISSUE THREAD

**Issue by totallyanon** [kingdom-of-ds-hacking/CTRMap-CE#6]
Attempting to load a zone into the world editor while using the AMD Adrenalin Edition 23.7.2 driver on an AMD Radeon RX 7900 XT card results in a black screen. Log: https://pastebin.com/k3m6QX4d

**Comment by HelloOO7** [comment]
That's AMD drivers for ya. Can you try with [this build](https://drive.google.com/file/d/1hy6p7IOCztGzInkfUvh2ICTgMc8mnAT1/view?usp=sharing)?

**Comment by totallyanon** [comment]
Looks like there's still a problem with exterior maps, but interiors look fine. https://streamable.com/7aay5z
Log: https://pastebin.com/dtaLMQRd

**Comment by HelloOO7** [comment]
I'd really like to try whatever drugs AMD is on, because the feature that it's complaining about (array initializers added in GLSL 1.20) is literally _not used anywhere in the shader_. I tried changing the shader generator to not store the Light structure into a variable and instead fetch it from the array directly (there is no reason why this should work, but both this and the error have "array" in the name). Could you try the build [here](https://drive.google.com/file/d/1IYmSCRSxSZn3L6Ji5e6cPDsy6pTrD1LX/view?usp=sharing)?

Also not that it's any of my business, but since you are using a fairly strong GPU, you might want to switch to the OpenGL 4 or Ubershaders backend (if AMD allows you to though).

**Comment by totallyanon** [comment]
Ok, this build seems to work with all of the rendering options.

**Comment by HelloOO7** [comment]
Now that's truly an AMD moment. Worked around in [#bfc2d9f](https://github.com/kingdom-of-ds-hacking/CTRMap-CE/commit/bfc2d9fad16ad3bbac67f7f4cb5faea39e779e23).
